{
 "title": "DEVelocity Core Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Wall of Shame (Remote Cache is NOT used)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "build_duration_counter_total{local_cache=\"true\", remote_cache=\"false\"}",
     "legendFormat": "{{project}}::local-cache({{local_cache}})"
    },
    {
     "expr": "build_duration_counter_total{local_cache=\"false\", remote_cache=\"false\"}",
     "legendFormat": "{{project}}::local-cache({{local_cache}})"
    }
   ]
  },
  {
   "title": "Total Number of Build by Project",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "build_duration_number_counter_total",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Last Build Duration (Seconds)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "build_duration / 1000", "legendFormat": "{{project}}" }
   ]
  },
  {
   "title": "Build Duration Change Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(build_duration_counter_total[5m])",
     "legendFormat": "{{project}}::remote-cache({{remote_cache}})"
    }
   ]
  }
 ]
}